
# Bluetooth Configuration
CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_GATT_CLIENT=y

# Debug Configuration
# CONFIG_LOG=n

# Memory Configuration
CONFIG_MAIN_STACK_SIZE=8192


# Device Name

CONFIG_BT_DEVICE_APPEARANCE=833

# Connection Parameters
CONFIG_BT_MAX_CONN=6
CONFIG_BT_BUF_ACL_RX_SIZE=255
CONFIG_BT_BUF_ACL_TX_SIZE=255
CONFIG_BT_L2CAP_TX_MTU=220
# GATT Configuration
CONFIG_BT_GATT_CLIENT=y

# Console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_PRINTK=y
CONFIG_REBOOT=y
CONFIG_SERIAL=y
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_RING_BUFFER=y

# for flash 
CONFIG_SPI=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_SPI_NOR=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_PM_PARTITION_REGION_LITTLEFS_EXTERNAL=y
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
# CONFIG_PM_PARTITION_SIZE_LITTLEFS=0x400000   
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_NORDIC_QSPI_NOR=n 

# MCUMGR
CONFIG_MCUMGR=y
CONFIG_MCUMGR_TRANSPORT_UART=y
CONFIG_UART_MCUMGR=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_MCUMGR_GRP_OS=y
CONFIG_MCUMGR_GRP_FS=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192

# CONFIG_IMAGE_MANAGER=y
# CONFIG_BOOT_MAX_IMG_SECTORS=512
CONFIG_NET_BUF=y
CONFIG_ZCBOR=y
CONFIG_CRC=y
CONFIG_BASE64=y


# CONFIG_PM_EXTERNAL_FLASH_ENABLED=y
CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y
# CONFIG_PM_EXTERNAL_FLASH_SIZE_BITS=134217728
CONFIG_SPI_NOR_SFDP_RUNTIME=y

CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_STREAM_FLASH=y

# use external flash for mcuboot
# CONFIG_BOOTLOADER_MCUBOOT_USE_EXTERNAL_FLASH=y
CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=y


CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=8192
CONFIG_MCUMGR_TRANSPORT_UART_MTU=4096
CONFIG_UART_MCUMGR_RX_BUF_SIZE=4096
CONFIG_UART_MCUMGR_RX_BUF_COUNT=8


CONFIG_MCUMGR_TRANSPORT_WORKQUEUE_STACK_SIZE=8192

CONFIG_MCUMGR_GRP_ENUM=y
CONFIG_MCUMGR_GRP_ENUM_DETAILS=y
CONFIG_MCUMGR_GRP_ENUM_DETAILS_NAME=y
CONFIG_MCUMGR_MGMT_NOTIFICATION_HOOKS=y
# CONFIG_MCUMGR_MGMT_NOTIFICATION_HOOKS=y
CONFIG_MCUMGR_GRP_FS_FILE_ACCESS_HOOK=y

# rtt
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y

CONFIG_BT_PERIPHERAL=y
# CONFIG_BT_CTLR_MULTIROLE=y
# CONFIG_BT_CTLR_SDC_MAX_CONN_EVENT_LEN=2000
CONFIG_BT_LL_SOFTDEVICE_MULTIROLE=y
CONFIG_BT_CTLR_SDC_PERIPHERAL_COUNT=5

CONFIG_BT_MAX_PAIRED=6

CONFIG_BT_FILTER_ACCEPT_LIST=y